### ISSUE TITLE
Compile failure on macos mojave for tests/examples enabled

### ISSUE THREAD

**Issue by mjs271** [sandialabs/Tines#1]
When attempting to build Tines, using Apple Clang 10.0.1 and Homebrew's openblas (haven't used macports before, but this one also includes lapacke), if either of the `TINES_ENABLE_TEST` `TINES_ENABLE_EXAMPLE` flags are set to `ON`, the build fails with a slew of errors. I am able to successfully build with these flags off. Also, when I use Tines in the current version of TChem, the TChem tests do build and pass, if that's a helpful data point.

**Comment by kyungjoo-kim** [comment]
@mschmidt271 I tried your environment (apple clang 10 and homebrewed openblas). I cannot compile kokkos with the apple clang compiler. 
```
[kyukim @butter] release > which clang++
clang++ is /usr/bin/clang++
[kyukim @butter] release > . ../run-conf-kokkos.sh
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /opt/local/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:
```

On Mac, I use macport ``clang++-mp-11`` compiler. I was able to compile with the following SHA. 
```
      1 commit 6794187115f40ba39368c32c914db7c623696323 (HEAD -> main, origin/main, origin/HEAD)
      2 Author: Kyungjoo Kim <kyukim@sandia.gov>
      3 Date:   Wed Feb 17 23:00:03 2021 -0800
      4 
      5     Tines - cmake error from higher version of cmake
```

I also brew the clang compiler from ``brew install llvm``. The cmake script somehow cannot compile a code. 
```
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++ - broken
CMake Error at /opt/local/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/local/opt/llvm/bin/clang++"

  is not able to compile a simple test program.
```

I do not use homebrew much. So I cannot tell what I do wrong regarding to the homebrew things. 

Would you try to use macport version of the clang ?

**Comment by mjs271** [comment]
So, looking into things... I tried to build from the same commit with the macports `clang-mp-10` and `clang-mp-11`, and I see the same errors if trying to build with either the test or example flags on. The errors appear to be mostly undefined symbols/symbols not found for architecture x86_64, and be related to kokkos. I also tried rebuilding gtest and kokkkos with the corresponding compiler and tried building kokkos from both the master and develop branches. Always got the same result... Sorry to not be more help!
@kyungjoo-kim

**Comment by kyungjoo-kim** [comment]
@mschmidt271 Let's go offline to solve this. I will email you.

**Comment by mjs271** [comment]
@kyungjoo-kim 
To wrap this up... just realized that I can get it working for apple clang with tests and examples on when I set `-D CMAKE_CXX_COMPILER=clang++`, rather than `clang` or the apple-aliased `gcc` (points to clang). I always thought that it defaulted to clang++ for c++ code, but apparently I was wrong.

**Comment by kyungjoo-kim** [comment]
Oh.... my~~~~~ You code seems to work with apple native clang++. As you see in the above, it does not work on my mac. I do not like apple versin of the compilers. I am going to close this issue.
