### ISSUE TITLE
Tests looking for files that do not exist

### ISSUE THREAD

**Issue by kevinholst** [sandialabs/Tines#3]
When I build and run ctest, most of the tests fail because they're looking for the wrong files. Evidently they're looking for files like "example/linear-algebra/Tines_Gemm.ptr.x", but what's available is Tines_Gemm.ptr.single.x and Tines_Gemm.ptr.double.x. I modified src/unit-test/Tines_Test_Driver.cpp to have it look for the single and double files where appropriate, but there are some other tests failing due to missing files.

Could you advise if I'm building improperly or if the tests need to be fixed?

**Comment by kyungjoo-kim** [comment]
@kevinholst Oh.... I am sorry that I check this issue late. You probably build correctly and the testing seems to be outdated. I will fix that soon.
