### ISSUE TITLE
Error: static assertion failed: Including non-public Kokkos header files is not allowed

### ISSUE THREAD

**Issue by 42n8dzydoo** [sandialabs/Tines#6]
Good day everyone,

I hope this message finds you well.

I am trying to compile Tines, TCHEM and the CSP library.

Although, I am new to cmake compilations and c++ programing, I have been able to pick some knowledge along the lines while trying to compile the libraries unsuccessfully yet.
I followed the manuals to letter but I keep getting stuck at the installation of the Tines. I have tried this on both an ubuntu linux and a Supercomputer cluster but could kept getting errors. I will be glad if you could help navigate the installation.

I was able to comile Kokkos, Gtest, yaml-cpp, and openblas which are all the dependencies of Tines. 

When, I issued the cmake command, I got the following:
`[bamidele@login001 TINES_BUILD_PATH]$ cmake \
>     -D CMAKE_INSTALL_PREFIX="${TINES_INSTALL_PATH}" \
>     -D CMAKE_CXX_COMPILER="${MY_CXX}" \
>     -D CMAKE_CXX_FLAGS="-g" \
>     -D CMAKE_C_COMPILER="${MY_CC}" \
>     -D CMAKE_EXE_LINKER_FLAGS="-lgfortran" \
>     -D TINES_ENABLE_DEBUG=OFF \
>     -D TINES_ENABLE_VERBOSE=OFF \
>     -D TINES_ENABLE_TEST=ON \
>     -D TINES_ENABLE_EXAMPLE=ON \
>     -D YAML_INSTALL_PATH="${YAML_INSTALL_PATH}" \
>     -D KOKKOS_INSTALL_PATH="${KOKKOS_INSTALL_PATH}" \
>     -D GTEST_INSTALL_PATH="${GTEST_INSTALL_PATH}" \
>     -D OPENBLAS_INSTALL_PATH="${OPENBLAS_INSTALL_PATH}" \
>     ${TINES_REPOSITORY_PATH}/src
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /work/apps/gcc/9.4.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /work/apps/gcc/9.4.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_LIBDIR is set lib64
-- TINES uses CMAKE_MODULE_PATH /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src;/home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/cmake/modules
-- TINES uses Kokkos installed at /home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH
-- Kokkos install path : /home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH
-- Kokkos found cmake config : /home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/lib64/cmake/Kokkos/KokkosConfig.cmake
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Enabled Kokkos devices: OPENMP;SERIAL
-- TINES uses gtest installed at /home/bamidele/CSP/INSTALL/GTEST_INSTALL_PATH
-- Gtest install path : /home/bamidele/CSP/INSTALL/GTEST_INSTALL_PATH
-- Gtest found cmake config : /home/bamidele/CSP/INSTALL/GTEST_INSTALL_PATH/lib64/cmake/GTest/GTestConfig.cmake
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- OpenBLAS is found at /home/bamidele/CSP/INSTALL/OPENBLAS_INSTALL_PATH/lib/libopenblas.so
-- OpenBLAS provides LAPACKE and header is found at /home/bamidele/CSP/INSTALL/OPENBLAS_INSTALL_PATH/include
-- OpenBLAS is found at /home/bamidele/CSP/INSTALL/OPENBLAS_INSTALL_PATH
-- OpenBLAS includes LAPACKE
-- TINES uses YAML installed at /home/bamidele/CSP/INSTALL/YAML_INSTALL_PATH
--   YAML include dir /home/bamidele/CSP/INSTALL/YAML_INSTALL_PATH/lib/cmake/yaml-cpp/../../../include
--   YAML library /home/bamidele/CSP/INSTALL/YAML_INSTALL_PATH/lib/libyaml-cpp.a
-- YAML is found at /home/bamidele/CSP/INSTALL/YAML_INSTALL_PATH
CMake Warning at CMakeLists.txt:195 (MESSAGE):
  -- SUNDIALS_INSTALL_PATH is not provided; SUNDIALS TPL is not enabled

CMake Warning at CMakeLists.txt:209 (MESSAGE):
  -- CUDA_INSTALL_PATH is not provided; CUDA TPLs are not enabled

-- TINES_LINK_LIBRARIES = tines;Kokkos::kokkos;GTest::gtest_main;openblas;yaml
-- Configuring done (3.8s)
-- Generating done (5.8s)
-- Build files have been written to: /home/bamidele/CSP/BUILD/TINES_BUILD_PATH`

Then when I issued the make install command, I get the following messages:
`[bamidele@login001 TINES_BUILD_PATH]$ make -j 4 install
[  2%] Building CXX object core/CMakeFiles/tines.dir/Tines_Progress.cpp.o
[  2%] Building CXX object core/CMakeFiles/tines.dir/Tines.cpp.o
[  2%] Building CXX object core/CMakeFiles/tines.dir/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp.o
[  2%] Building CXX object core/CMakeFiles/tines.dir/linear-algebra/Tines_ApplyQ_HostTPL.cpp.o
[  3%] Building CXX object core/CMakeFiles/tines.dir/linear-algebra/Tines_Gemm_Device.cpp.o
[  3%] Building CXX object core/CMakeFiles/tines.dir/linear-algebra/Tines_Gemm_HostTPL.cpp.o
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:39,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ApplyQ_HostTPL.cpp:2:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:40,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ApplyQ_HostTPL.cpp:2:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_View.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutContiguous.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:190,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ApplyQ_HostTPL.cpp:2:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutNatural.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:191,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ApplyQ_HostTPL.cpp:2:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:39,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:40,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_View.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutContiguous.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:190,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutNatural.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:191,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:39,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:40,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_View.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutContiguous.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:190,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutNatural.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:191,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado_DynamicArrayTraits.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DynamicStorage.hpp:37,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DFad.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:55,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ApplyQ_HostTPL.cpp:2:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_MemoryPool.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado_DynamicArrayTraits.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DynamicStorage.hpp:37,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DFad.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:55,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_MemoryPool.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado_DynamicArrayTraits.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DynamicStorage.hpp:37,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DFad.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:55,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Interface.hpp:26,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_HostTPL.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_MemoryPool.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:39,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines.hpp:25,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_Device.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:40,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines.hpp:25,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_Device.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_View.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutContiguous.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:190,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines.hpp:25,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_Device.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_LayoutNatural.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/KokkosExp_View_Fad.hpp:191,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Kokkos_View_Fad.hpp:33,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines.hpp:25,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_Device.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_Layout.hpp:22:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   22 | static_assert(false,
      |               ^~~~~
In file included from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado_DynamicArrayTraits.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DynamicStorage.hpp:37,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/experimental/Sacado_Fad_Exp_DFad.hpp:34,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/sacado/Sacado.hpp:55,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines_Internal.hpp:44,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/Tines.hpp:25,
                 from /home/bamidele/CSP/REPOS/TINES_REPOSITORY_PATH/src/core/linear-algebra/Tines_Gemm_Device.cpp:21:
/home/bamidele/CSP/INSTALL/KOKKOS_INSTALL_PATH/include/Kokkos_MemoryPool.hpp:19:15: error: static assertion failed: Including non-public Kokkos header files is not allowed.
   19 | static_assert(false,
      |               ^~~~~
make[2]: *** [core/CMakeFiles/tines.dir/linear-algebra/Tines_ComputeConditionNumber_HostTPL.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [core/CMakeFiles/tines.dir/linear-algebra/Tines_ApplyQ_HostTPL.cpp.o] Error 1
make[2]: *** [core/CMakeFiles/tines.dir/linear-algebra/Tines_Gemm_HostTPL.cpp.o] Error 1
make[2]: *** [core/CMakeFiles/tines.dir/linear-algebra/Tines_Gemm_Device.cpp.o] Error 1
make[1]: *** [core/CMakeFiles/tines.dir/all] Error 2
make: *** [all] Error 2`

Initially, I thought the error was from Kokkos and I created an issue on there repo. But they directed me back to tines.

PS: I compiled Kokkos version 4

Thank you very much.

Regards.

**Comment by 42n8dzydoo** [comment]
Here's what few of the error logs look like (for readability)

![Capture](https://github.com/sandialabs/Tines/assets/72227608/2ab54c56-a5bc-4926-9846-41cee90fe147)

**Comment by odiazib** [comment]
csplib/tchem/tines uses kokkos version 3.6 in its main branch. 

 **For kokkos v4**.

From the csplib repo (https://github.com/sandialabs/CSPlib). You must switch CSPlib from the main to `csplib-kokkosv4` branch. Then, apply `git submodule update --init –recursive` to initialize submodules. 

After submodule initialization:
* Tchem’s source code will be saved at: 
CSPlib_repo/ext/TChem 

* Tines’ source code will be saved at:
CSPlib_repo/ext/TChem/ext/Tines

* Kokkos’ source code will be saved at:
CSPlib_repo/ext/TChem/ext/Tines/ext/


I hope this helps.

**Comment by 42n8dzydoo** [comment]
Thank you very much for this. It worked and I was able to compile the Tines.

In addition, I think the correct command for the submodule update is: `git submodule update --init --recursive`
In case, anyone stumbles upon this and got an error:

> `Permission denied (publickey).
> fatal: The remote end hung up unexpectedly
> Clone of 'git@github.com:sandialabs/TChem.git' into submodule path 'ext/TChem' failed`

You have to ensure you are using the "HTTPS" link in place of the "SSH" key:
To do this, navigate to your cloned repository, and edit the `.gitmodules` file and change the file url:
Edit from:

> `[submodule "ext/TChem"]
>         path = ext/TChem
>         url = git@github.com:sandialabs/TChem.git`

to:

> `[submodule "ext/TChem"]
>         path = ext/TChem
>         url = https://github.com/sandialabs/TChem.git`

This implies you may not be able to update the submodules recursively for  TChem, Tines and Kokkos. 
`git submodule update --init`.

So, you may have to do the same for Tines and Kokkos by editing the `.gitmodules` in `CSPlib_repo/ext/TChem` and `CSPlib_repo/ext/TChem/ext/Tines` respectively.

Thank you.
